# Generated by Django 2.2.16 on 2021-10-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_categories_genre_titles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='year',
            field=models.IntegerField(max_length=4),
        ),
    ]
