# Generated by Django 2.2.16 on 2021-10-09 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20211009_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='categories',
        ),
        migrations.AddField(
            model_name='titles',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='reviews.Categories'),
        ),
    ]
