# Generated by Django 2.2.16 on 2021-10-10 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20211010_1820'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Title',
            new_name='Titles',
        ),
    ]
